function [GeoCondition] = GenerateGeo(TCinf)

Tube_num = TCinf.Tube_num;
con_num =  TCinf.con_num;
row = TCinf.row;
col = TCinf.col;

%GeoConditionStrcut;
L       = 0.5;
D_inner = 9e-3;
r       = 1e-6;
D_outer = 10e-3;
dx_tube = (D_outer - D_inner)/2;    % 管壁厚度

P_row = 20e-3;          % row管间距
P_col = 20e-3;          % col管间距

% 翅片信息
dx_fin      = 0.1e-3;               % 翅片厚度
Fin_pitch   = 2e-3;                 % 翅片间距

Fin_pitch_net = Fin_pitch - dx_fin; % 翅片净间距
L_fin = (row+0.5)*P_row;
H_fin = col*P_col;
A_fin = L_fin*H_fin - row*col*pi*(D_outer+1e-3)^2/4;

% 平均翅片高就是P_col
fin_num = floor(L/Fin_pitch);
A_MA = fin_num*A_fin*2 + pi*D_outer*Tube_num*(L-fin_num*dx_fin);
A_R  = row*col*L*pi*D_inner;

GeoCondition = struct("L",L,...
    "D_inner"  ,D_inner,...
    "D_outer"  ,D_outer,...
    "r"        ,r,...
    "col"      ,col, ...
    "row"      ,row,...
    "Tube_num" ,Tube_num,...
    "con_num"  ,con_num,...
    "A_R"      ,A_R,...
    "A_MA"     ,A_MA,...
    "A_fin"    ,A_fin,...
    "P_col"    ,P_col,...
    "P_row"    ,P_row,...
    "Fin_pitch",Fin_pitch, ...
    "dx_fin"   ,dx_fin,...
    "dx_tube"  ,dx_tube,...
    "L_fin"    ,L_fin,...
    "H_fin"    ,H_fin,...
    "Fin_pitch_net",Fin_pitch_net);
end